// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgxuugqckdmmuvoeoknj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpneHV1Z3Fja2RtbXV2b2Vva25qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyNDEwMjAsImV4cCI6MjA4ODgxNzAyMH0.B3oXpa6pj4zjzqAsN4zl5JMpZ3zBxXG693z3ZlYvJRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});